version: '3.8'
services:
  # By default, SonarQube is using h2 database which is not recommended for production
#  sonarqube:
#    image: sonarqube:latest
#    container_name: sonarqube
#    ports:
#      - "9000:9000"
#    volumes:
#      - sonarqube_data:/opt/sonarqube/data
#      - sonarqube_extensions:/opt/sonarqube/extensions
#      - sonarqube_logs:/opt/sonarqube/logs
#      - sonarqube_temp:/opt/sonarqube/temp


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "9090:8080"
    volumes:
      - ./src/main/resources/keycloak_realm_backup/:/opt/keycloak/data/import
    entrypoint: '/opt/keycloak/bin/kc.sh start-dev --import-realm'


#networks:
#  sonar:
#    driver: bridge

#volumes:
#  sonarqube_data:
#  sonarqube_extensions:
#  sonarqube_logs:
#  sonarqube_temp:
