server:
    port: 8088
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
    jackson:
        date-format: dd-MM-yyyy HH:mm:ss
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop
    output:
        ansi:
            enabled: ALWAYS
