spring:
  datasource:
    url: jdbc:tc:postgresql://localhost:5432/mydb
    username: postgres
    password: pass
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  h2:
    console:
      enabled: true