server:
  port: 8080

spring:
  application:
    name: department-api
  datasource:
    url: jdbc:h2:file:./data/my-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        #        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true

springdoc:
  swagger-ui:
    use-root-path: true
    default-models-expand-depth: -1
  version: '@springdoc-openapi-starter-webmvc-ui.version@'