server:
  port: 8080

spring:
  application:
    name: department-api
  datasource:
    url: jdbc:h2:file:./data/my-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        #        format_sql: true
        hbm2ddl:
          auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  # MailHog provides a local SMTP server for capturing and viewing emails during local development/testing.
  mail:
    host: localhost
    port: 1025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

#  You can also use Mailtrap which is an Email Delivery Platform. You have to create an account https://mailtrap.io/
#  mail:
#    host: smtp.mailtrap.io
#    port: 25
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    username: <put-your-smtp-username>
#    password: <put-your-smtp-password>


springdoc:
  swagger-ui:
    use-root-path: true
    default-models-expand-depth: -1
  version: '@springdoc-openapi-starter-webmvc-ui.version@'