server:
  port: 8080

spring:
  application:
    name: department-api
  security:
    oauth2:
      resourceserver:
        jwt:
          # validate jwt token using the oauth2 resource server
          issuer-uri: ${KEYCLOAK_SERVER_URL:http://localhost:9090/realms/ainigma100}
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
          token-endpoint: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/token
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration/h2
  datasource:
    url: jdbc:h2:file:./data/my-db;AUTO_SERVER=true
    username: root
    password: pass
    driver-class-name: org.h2.Driver
  jpa:
    #    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        #        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  output:
    ansi:
      enabled: always
  h2:
    console:
      enabled: true
  # MailHog provides a local SMTP server for capturing and viewing emails during local development/testing.
  mail:
    host: ${EMAIL_HOST:localhost}
    port: 1025
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

#  You can also use Mailtrap which is an Email Delivery Platform. You have to create an account https://mailtrap.io/
#  mail:
#    host: smtp.mailtrap.io
#    port: 25
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    username: <put-your-smtp-username>
#    password: <put-your-smtp-password>


springdoc:
  swagger-ui:
    path: /ui
    tags-sorter: alpha
  version: '@springdoc-openapi-starter-webmvc-ui.version@'

keycloak:
  client-id: department-api
  principle-attribute: preferred_username
