server.port=8088
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.password=
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.h2.console.enabled=true
spring.jackson.date-format=dd-MM-yyyy HH:mm:ss
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
